name: deploy_user_guide

on:
  push:
    branches:
      - main
    paths:
      - ".docs/**"
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0

      - name: Install Dependencies
        working-directory: .docs
        run: npm ci

      - name: Build Documentation
        working-directory: .docs
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.docs/dist
          publish_branch: gh-pages
          
