name: deploy_user_guide

on:
  push:
    branches:
      - main
    paths:
      - ".docs/**"
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@v4

      - name: Install Dependencies
        working-directory: .docs
        run: npm ci

      - name: Build Documentation
        working-directory: .docs
        run: npm run build

      - name: Deploy
        working-directory: .docs
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          npm run deploy
          
